# Leap of Faith in PyTorch [L2] -Tensor Operations (Day 2) - Demo

### Basic Tensor Operations (recap from L1)

In [2]:
import torch

# Financial data: GDP in trillion dollars (year 2023)
gdp = torch.tensor([21.43, 14.34, 5.08, 1.64, 1.48])  # USA, China, India, Canada, Russia

# Social data: Population in millions
population = torch.tensor([330, 1400, 1380, 38, 144])  # USA, China, India, Canada, Russia

# Political data: Governance score (hypothetical)
governance_score = torch.tensor([85, 70, 60, 80, 65])  # USA, China, India, Canada, Russia

# Increase GDP by 10%
gdp_increased = gdp + gdp * 0.1
print("Increased GDP:\n", gdp_increased)

# Reduce population by 5%
population_reduced = population - population * 0.05
print("Reduced Population:\n", population_reduced)

# Multiply GDP by governance score
gdp_governance = gdp * governance_score
print("GDP multiplied by Governance Score:\n", gdp_governance)

# Divide GDP by population to get GDP per capita in thousands of dollars
gdp_per_capita = (gdp * 1000) / population
print("GDP Per Capita (in thousands of dollars):\n", gdp_per_capita)

Increased GDP:
 tensor([23.5730, 15.7740,  5.5880,  1.8040,  1.6280])
Reduced Population:
 tensor([ 313.5000, 1330.0000, 1311.0000,   36.1000,  136.8000])
GDP multiplied by Governance Score:
 tensor([1821.5500, 1003.8000,  304.8000,  131.2000,   96.2000])
GDP Per Capita (in thousands of dollars):
 tensor([64.9394, 10.2429,  3.6812, 43.1579, 10.2778])


### Advanced Operations

In [2]:
# Creating two tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Adding the tensors
tensor_sum = tensor_a + tensor_b
print("Tensor Addition:\n", tensor_sum)

Tensor Addition:
 tensor([[ 6,  8],
        [10, 12]])


### Tensor Multiplication

In [3]:
# Multiplying the tensors element-wise
tensor_product = tensor_a * tensor_b
print("Tensor Multiplication:\n", tensor_product)

Tensor Multiplication:
 tensor([[ 5, 12],
        [21, 32]])


### Example using Financial, Social, and Political Topics

In [12]:
# Financial data: GDP in trillion dollars (year 2023)
# USA, China, India, Canada, Russia
gdp = torch.tensor([21.43, 14.34, 5.08, 1.64, 1.48]) 
print(gdp)

# Social data: Population in millions
# USA, China, India, Canada, Russia
population = torch.tensor([330, 1400, 1380, 38, 144])
print(population)

# Political data: Governance score (hypothetical, adjust it to your own convenience)
# USA, China, India, Canada, Russia
governance_score = torch.tensor([65, 70, 60, 60, 65])
print(governance_score)

tensor([21.4300, 14.3400,  5.0800,  1.6400,  1.4800])
tensor([ 330, 1400, 1380,   38,  144])
tensor([65, 70, 60, 60, 65])


### Calculating GDP Per Capita

In [11]:
# Adjust the GDP to billions to match the population in millions for easier interpretation
gdp_in_billions = gdp * 1000  # Convert GDP from trillions to billions

# Calculating GDP per capita
gdp_per_capita = gdp_in_billions / population
print("GDP Per Capita (in thousands of dollars):\n", gdp_per_capita)

GDP Per Capita (in thousands of dollars):
 tensor([64.9394, 10.2429,  3.6812, 43.1579, 10.2778])


### Adjusted Governance Score (GS)

In [13]:
# Adjusted governance score
adjusted_governance_score = governance_score * gdp_per_capita
print("Adjusted Governance Score:\n", adjusted_governance_score)

Adjusted Governance Score:
 tensor([4221.0605,  717.0000,  220.8696, 2589.4736,  668.0555])
